# TA Tutorial Session — Advanced Data Analysis: Selection, Grouping, and Joins in Pandas

**Reference:** Academic Session 10,11,12 — Selection, Grouping, and Joins in Pandas
**Estimated Duration:** 90 minutes

---

### Agenda
1. Quick topic summary (refresh from the faculty session)
2. 5 objective questions — *vote in the chat*
3. 1 scenario-based practice question — *aligned to your assessments*
4. Open Q&A block

> **Link to main session:** ou learned how to convert raw data into a structured format suitable for machine learning using Pandas, covering row selection, filtering with conditions, aggregating data into summaries, and joining multiple tables together.
>
> **Why it matters:** These fundamental Pandas operations form the core of your subjective assignments and are essential for preprocessing data in any machine learning pipeline.

# Section 1 — Topic-wise Summary

> **Why are we learning this?**
> - Imagine you are an **HR manager** and need to find all **IT employees** earning over **50,000**. Going through
thousands of rows **manually is impossible**. Data filtering solves this instantly.

> - Your **manager asks for the average salary of each department** to plan next year's budget. Instead of
calculating this by hand, grouping and aggregation give you the summary in one step.

> - You are a **data analyst** with **employee names** in one table and their **salaries** in another. To find out what a
specific person earns, you need to link these tables together. Structural joins make this seamless

**Topic 1: Data Selection and Filtering**

> - Data selection means **choosing specific rows and columns** using **.loc[]** (label-based, end index inclusive) or **.iloc[]** (integer-position-based, end index exclusive).

> - **Filtering** applies relational conditions (like **df['salary'] > 50000 **) to **evaluate column-wise** and retain **only the rows** where the v**alue is True**.

> - You can **combine filters** using logical **operators & (AND) and | (OR)** to extract highly specific data of
interest.

> - Each condition in a combined filter must be wrapped in its own parentheses to avoid Python operator
precedence errors.

## 1. Why Do We Need Data Selection and Filtering?

Imagine a company has **10,000 employee records**.

**Suppose your manager asks:**

"Show me only IT employees earning more than ₹50,000."

Looking **manually** through 10,000 rows is **impossible**.

**Data Selection and Filtering allow us to:**

- Extract required rows
- Extract required columns
- Apply conditions
- Focus only on relevant information

This is one of the **most frequently used operations** in Data Analysis and Machine Learning preprocessing.

## 2. Data Selection

Data Selection means **choosing specific rows or columns** from a DataFrame.

In [ ]:
import pandas as pd

data = {
    "Name": ["Amit", "Maya", "Kiran", "Sarah"],
    "Department": ["HR", "IT", "IT", "Marketing"],
    "Salary": [45000, 70000, 72000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name Department  Salary
0   Amit         HR   45000
1   Maya         IT   70000
2  Kiran         IT   72000
3  Sarah  Marketing   50000

## 3. Selecting Columns

In [ ]:
# Single column
df["Salary"]  # series

0    45000
1    70000
2    72000
3    50000
Name: Salary, dtype: int64

In [ ]:
# Multiple Columns - Use double brackets.
df[["Name", "Salary"]] # dataframe

    Name  Salary
0   Amit   45000
1   Maya   70000
2  Kiran   72000
3  Sarah   50000

In [ ]:
# Important

df["Name", "Salary"] # ❌ Wrong

KeyError: ('Name', 'Salary')

In [ ]:
df[["Name", "Salary"]] # ✅ Correct

    Name  Salary
0   Amit   45000
1   Maya   70000
2  Kiran   72000
3  Sarah   50000

## 4. Row Selection Using loc[]
**Syntax** - df.loc[row_start:row_end]

**Characteristics**
- Label-based
- End index INCLUDED

In [ ]:
# Example
print(df)

df.loc[1:3] # Total = 3 rows

    Name Department  Salary
0   Amit         HR   45000
1   Maya         IT   70000
2  Kiran         IT   72000
3  Sarah  Marketing   50000

    Name Department  Salary
1   Maya         IT   70000
2  Kiran         IT   72000
3  Sarah  Marketing   50000

# 5. Row Selection Using iloc[]

**Syntax** - df.iloc[start:end]

**Characteristics**
- Position-based
- End index EXCLUDED
- iloc - Integer location

In [ ]:
# Example
df.iloc[1:3]

    Name Department  Salary
1   Maya         IT   70000
2  Kiran         IT   72000

## Remember

| Function | Based On | End Included? |
| -------- | -------- | ------------- |
| loc      | Label    | Yes           |
| iloc     | Position | No            |

## 6. Data Filtering

Filtering means **keeping only rows** that satisfy a condition.

In [ ]:
df[df["Salary"] > 50000]  # Only salaries above 50,000 remain.

    Name Department  Salary
1   Maya         IT   70000
2  Kiran         IT   72000

## 7. Multiple Conditions Using AND (&)

**Suppose** we need:

- Department = IT
- Salary > 50000

In [ ]:
df[
    (df["Department"] == "IT") # Take the Department column from df
    &
    (df["Salary"] > 50000)
]
# Every condition must be wrapped inside parentheses.

    Name Department  Salary
1   Maya         IT   70000
2  Kiran         IT   72000

**Combine bot condition**
- False & False = False
- True  & True  = True
- True  & True  = True
- False & False = False

df[
    [False, True, True, False]
]

**series we got from df []**

It means **Keep rows** where value is **True**, **Remove** rows where value is **False**

## 8. OR Condition (|)

**Suppose** we need:

- IT employees OR
- Salary > 70000

In [ ]:
df[
    (df["Department"]=="IT")
    |
    (df["Salary"]>70000)
]

    Name Department  Salary
1   Maya         IT   70000
2  Kiran         IT   72000

# Topic 2: Sorting and Reordering Data

This topic focuses on **organizing data in a meaningful order** so that **analysis becomes easier** and insights can be extracted quickly.
- Sorting and reordering are commonly used in data analysis, reporting, dashboards, and machine learning preprocessing.

## 1. Why Do We Need Sorting?

Imagine you are an **HR manager** and want to:

- Find the highest-paid employees
- Find the lowest-performing students
- Rank products by sales
- Display top customers by revenue

Without sorting, finding this information is difficult.

- Sorting helps arrange records in a meaningful order.

In [ ]:
# sample datasframe
import pandas as pd

data = {
    "Employee": ["Amit", "Maya", "Kiran", "Sarah", "Alex"],
    "Department": ["HR", "IT", "IT", "Marketing", "Finance"],
    "Salary": [45000, 70000, 72000, 50000, 65000]
}

df = pd.DataFrame(data)

print(df)

  Employee Department  Salary
0     Amit         HR   45000
1     Maya         IT   70000
2    Kiran         IT   72000
3    Sarah  Marketing   50000
4     Alex    Finance   65000

## 2. Sorting Using sort_values()

**Syntax** : df.sort_values(by="column_name")

 - Default **ascending=True** which means **smallest → largest**.

In [ ]:
#Example: Sort Salary in Ascending Order
df.sort_values(by="Salary")  # The salaries are arranged from lowest to highest.

  Employee Department  Salary
0     Amit         HR   45000
3    Sarah  Marketing   50000
4     Alex    Finance   65000
1     Maya         IT   70000
2    Kiran         IT   72000

## 3. Sorting in Descending Order

Suppose management wants the **highest-paid** **employees** first.

In [ ]:
df.sort_values(by="Salary", ascending=False) # Now salaries are arranged from highest to lowest.

  Employee Department  Salary
2    Kiran         IT   72000
1     Maya         IT   70000
4     Alex    Finance   65000
3    Sarah  Marketing   50000
0     Amit         HR   45000

**Most Important Point**

- **Ascending** : ascending=*True* (Small → Large)
- **Descending** : ascending=*False* (Large → Small)

## 4. Sorting by Multiple Columns
Sometimes one column is not enough.

In [ ]:
#Example
data = {
    "Employee": ["Amit","Maya","Kiran","Sarah","Alex"],
    "Department": ["IT","IT","HR","HR","IT"],
    "Salary": [70000,70000,45000,45000,70000]
}

df = pd.DataFrame(data)

**Suppose** we want:

- Department-wise sorting
- Salary-wise sorting within each department

In [ ]:
df.sort_values(
    by=["Department","Salary"]
)

  Employee Department  Salary
4     Alex    Finance   65000
0     Amit         HR   45000
1     Maya         IT   70000
2    Kiran         IT   72000
3    Sarah  Marketing   50000

## 5. Different Sorting Orders for Multiple Columns

In [ ]:
df.sort_values(
    by=["Department","Salary"],
    ascending=[True, False]
)
# means Department → Ascending, Salary → Descending

  Employee Department  Salary
4     Alex    Finance   65000
0     Amit         HR   45000
2    Kiran         IT   72000
1     Maya         IT   70000
3    Sarah  Marketing   50000

**Why Double Brackets?**


- **Wrong** - df["Department", "Employee"]

- **Correct**

df[
    ["Department", "Employee"]
]

- Always use a list of column names.

## Common mistakes

- **Wrong** : df.sort()   >- **Correct** : df.sort_values()


- **Wrong** : df.sort_values("Salary") >- **Correct** : df.sort_values(by="Salary")
- **Wrong** : df["Department","Employee"] >- **Correct** : df[["Department","Employee"]]

# Topic 3: Data Aggregation and Grouping

- **Data Aggregation** and **Grouping** are among the most important Pandas operations because they allow us to **convert large datasets into meaningful summaries.**

- **Instead of analyzing thousands of rows** individually, we can quickly answer business questions such as:

- What is the **average salary** in each department **?**
- Which **city** generated the **highest sales** **?**
- How many **employees** **belong** to each department **?**
- What is the **maximum score** achieved in each class **?**

Grouping and aggregation are widely used in **data analytics**, business intelligence, **machine learning**, and reporting systems.

## 1. Why Do We Need Grouping?

Consider the following employee dataset:

In [ ]:
import pandas as pd

data = {
    "Employee": ["Amit", "Maya", "Kiran", "Sarah", "Alex"],
    "Department": ["HR", "IT", "IT", "HR", "Finance"],
    "Salary": [45000, 70000, 72000, 50000, 65000]
}

df = pd.DataFrame(data)

print(df)

  Employee Department  Salary
0     Amit         HR   45000
1     Maya         IT   70000
2    Kiran         IT   72000
3    Sarah         HR   50000
4     Alex    Finance   65000

**Suppose management asks:**

- "What is the average salary of each department?"

- Doing this **manually** is **time-consuming**.

- **Grouping** solves this problem instantly.

## 2. Understanding GroupBy

The **groupby()** function **divides data into smaller groups** based on a **categorical column**.

**Syntax** - df.groupby("column_name")

In [ ]:
# Example
df.groupby("Department")   # groupby() = grouping operation

**This creates groups**:

**HR**
 ├─ Amit
 └─ Sarah

**IT**
 ├─ Maya
 └─ Kiran

**Finance**
 └─ Alex

## 3. What is Aggregation?

Aggregation means combining multiple values into a summary statistic.

**Common aggregation functions:**

| Function | Meaning          |
| -------- | ---------------- |
| sum()    | Total            |
| mean()   | Average          |
| count()  | Number of values |
| min()    | Smallest value   |
| max()    | Largest value    |

- These functions convert many rows into a compact summary.

## 4. Mean Salary by Department

In [ ]:
df.groupby("Department")["Salary"].mean()

Department
Finance    65000.0
HR         47500.0
IT         71000.0
Name: Salary, dtype: float64

## 5. Total Salary by Department

In [ ]:
df.groupby("Department")["Salary"].sum()

Department
Finance     65000
HR          95000
IT         142000
Name: Salary, dtype: int64

## 6. Employee Count per Department

In [ ]:
df.groupby("Department")["Employee"].count()

Department
Finance    1
HR         2
IT         2
Name: Employee, dtype: int64

## 7. Minimum Salary per Department

In [ ]:
df.groupby("Department")["Salary"].min()

Department
Finance    65000
HR         45000
IT         70000
Name: Salary, dtype: int64

## 8. Maximum Salary per Department

In [ ]:
df.groupby("Department")["Salary"].max()

Department
Finance    65000
HR         50000
IT         72000
Name: Salary, dtype: int64

## 9. Multiple Aggregations Using agg()

Suppose management wants:

- Average Salary
- Maximum Salary
- Minimum Salary

Together.

Instead of running three separate commands:

In [ ]:
df.groupby("Department")["Salary"].agg(
    ["mean", "min", "max"]
)

               mean    min    max
Department
Finance     65000.0  65000  65000
HR          47500.0  45000  50000
IT          71000.0  70000  72000

## 10. Why reset_index()?

After grouping:

In [ ]:
result = df.groupby(
    "Department"
)["Salary"].mean()

print(result)

Department
Finance    65000.0
HR         47500.0
IT         71000.0
Name: Salary, dtype: float64

**Sometimes we want it back as a normal column.**

In [ ]:
result = (
    df.groupby("Department")
      ["Salary"]
      .mean()
      .reset_index()
)
print(result)

  Department   Salary
0    Finance  65000.0
1         HR  47500.0
2         IT  71000.0

## Why use reset_index()?

After **groupby()**,
the grouping column becomes the index.

**reset_index()**
converts it back into a normal column.

# Topic 4: Combining DataFrames and Structural Joins

- In **real-world data analysis**, information is often **stored across multiple tables** rather than a s**ingle DataFrame**.

- **For example:** **Employee** details may be stored in **one** table. **Department** information may be stored in **another** table. **Salary** records may be stored in a **third** table.

- To perform meaningful analysis, **these tables must be combined**. Pandas provides powerful functions such as **merge(), concat(), and join()** to combine DataFrames efficiently.
- This **concept** is **similar to SQL joins** and is widely used in data engineering, analytics, and machine learning pipelines.

## 1. Why Do We Need Combining DataFrames?

Consider the following situation.

In [ ]:
# Employee Table
import pandas as pd

employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "Name": ["Amit", "Maya", "Kiran"]
})

print(employees)

   Emp_ID   Name
0     101   Amit
1     102   Maya
2     103  Kiran

In [ ]:
# Department Table
departments = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "Department": ["HR", "IT", "Finance"]
})

print(departments)

   Emp_ID Department
0     101         HR
1     102         IT
2     103    Finance

**Question:** How do we get Employee Name and Department together?

**Answer:** merge()

## 2. Understanding merge()

The **merge()** function **combines DataFrames** using a **common column**.

**Syntax**

pd.merge(
    left_df,
    right_df,
    on="common_column"
)

In [ ]:
# Syntax

pd.merge(
    left_df,
    right_df,
    on="common_column"
)

## 3. Inner Join - Matching rows only

In [ ]:
merged_df = pd.merge(
    employees,
    departments,
    on="Emp_ID"
)

print(merged_df)

   Emp_ID   Name Department
0     101   Amit         HR
1     102   Maya         IT
2     103  Kiran    Finance

**Visual Understanding**
*Table A*
- 101
- 102
- 103

*Table B*
- 101
- 102
- 104

*Inner Join Result*
- 101
- 102

## 4. Types of Joins

Pandas supports four major joins:

| Join  | Description               |
| ----- | ------------------------- |
| inner | Matching rows only        |
| left  | All rows from left table  |
| right | All rows from right table |
| outer | All rows from both tables |

## 5. Left Join - All rows from left table

Keep **everything** from the **left DataFrame**.

In [ ]:
# Example

employees = pd.DataFrame({
    "Emp_ID":[101,102,103],
    "Name":["Amit","Maya","Kiran"]
})

departments = pd.DataFrame({
    "Emp_ID":[101,102],
    "Department":["HR","IT"]
})

pd.merge(
    employees,
    departments,
    on="Emp_ID",
    how="left"
)

   Emp_ID   Name Department
0     101   Amit         HR
1     102   Maya         IT
2     103  Kiran        NaN

 **Notice** : 103 was kept because it exists in the left table.

## 6. Right Join - All rows from right table

Keep everything from the right table.

In [ ]:
pd.merge(
    employees,
    departments,
    on="Emp_ID",
    how="right"
)
# Only rows present in the right table are guaranteed to appear.

   Emp_ID  Name Department
0     101  Amit         HR
1     102  Maya         IT

## 7. Outer Join - All rows from both tables

Keep everything from both tables.

In [ ]:
pd.merge(
    employees,
    departments,
    on="Emp_ID",
    how="outer"
)
# All rows from both tables.
# Missing values become: NaN

   Emp_ID   Name Department
0     101   Amit         HR
1     102   Maya         IT
2     103  Kiran        NaN

**Which join keeps all records?**

**Answer**: Outer Join

**Which join keeps only matching records?**

**Answer**: Inner Join

## 8. Understanding concat()

While merge **combines tables** using **common columns**, **merge()** looks for relationships.

**concat()** - simply stacks DataFrames.

In [ ]:
# Example

df1 = pd.DataFrame({
    "Name":["Amit","Maya"]
})

df2 = pd.DataFrame({
    "Name":["Kiran","Sarah"]
})

pd.concat([df1, df2])

    Name
0   Amit
1   Maya
0  Kiran
1  Sarah

**Reset Index During Conca**t

In [ ]:
pd.concat(
    [df1, df2],
    ignore_index=True
)
# clear indexing

    Name
0   Amit
1   Maya
2  Kiran
3  Sarah

## 9. Vertical vs Horizontal Concatenation

In [ ]:
# Vertical default , Rows increase
pd.concat(
    [df1, df2]
)

    Name
0   Amit
1   Maya
0  Kiran
1  Sarah

In [ ]:
# Horizontal - Columns increase
pd.concat(
    [df1, df2],
    axis=1
)

   Name   Name
0  Amit  Kiran
1  Maya  Sarah

## Difference Between merge() and concat()

| merge()                 | concat()                |
| ----------------------- | ----------------------- |
| Uses common key         | No common key needed    |
| Similar to SQL Join     | Similar to stacking     |
| Combines related tables | Combines similar tables |

# Section 2 — Objective Questions (15 min)

> **TA note:** Display each question, give learners a moment, collect votes in chat, *then* reveal the answer and walk through every option.

### Question 1
Given df with default labels, `result_loc = df.loc[1:3]` and `result_iloc = df.iloc[1:3]`. How many rows are returned by
each?

- **A)** `loc has 2 rows; iloc has 2 rows.`
- **B)** `loc has 2 rows; iloc has 3 rows.`
- **C)** `loc has 3 rows; iloc has 3 rows.`
- **D)** `loc has 3 rows; iloc has 2 rows.`

<details><summary><b>Answer & explanation</b></summary>

**Correct: D**
- **A** — Wrong. loc uses an inclusive endpoint, so it returns 3 rows.
- **B** — Wrong. This inverts the behaviour; loc includes the endpoint while iloc excludes it.
- **C** — Wrong. iloc follows Python slice semantics and excludes the endpoint, returning only 2 rows.
- **D** — **Correct**. loc is label-based and inclusive (returns rows 1, 2, 3), whereas iloc is integer-based and
exclusive (returns rows 1, 2). Source: Assignment: Academic Session 10 - Advanced Data Selection And
Filtering - Objectiv
</details>

### Question 2
What does the expression `df[(df['department'] == 'IT') & (df['salary'] > 40000)]` return?

- **A)** All non-HR employees earning above 40000.
- **B)** Only rows for IT employees with salary above 40000.
- **C)** All employees because every salary is above 40000.
- **D)** An empty DataFrame as the condition is impossible.

<details><summary><b>Answer & explanation</b></summary>

**Correct: B**
- **A** — Wrong. It specifically looks for the 'IT' department, not just any non-HR department.
- **B** — **Correct**. The & operator requires both conditions to be True simultaneously to retain the row.
- **C** — Wrong. Even if all salaries are above 40000, only employees who are also in IT will pass the combined
condition.
- **D** — Wrong. It is possible for employees to belong to the IT department and earn over 40000 concurrently.
Source: Assignment: Academic Session 10 - Advanced Data Selection And Filtering - Objective
</details>

## Question 3
Which of the following best describes data aggregation in Pandas?

- **A)** Removes duplicate rows from a dataset to produce a clean table.
- **B)** Combines multiple data values to produce a compact summary.
- **C)** Partitions a dataset into subsets based on a categorical column.
- **D)** Converts a DataFrame index from integers to string labels.

<details><summary><b>Answer & explanation</b></summary>

**Correct: B**
- **A** — Wrong. Removing duplicates is a separate data cleaning deduplication step, not aggregation.
- **B** — **Correct**. Aggregation generates summary statistics (like total or average) from multiple underlying data
values.
- **C** — Wrong. Partitioning data into subsets is the definition of grouping, which happens before aggregation.
- **D** — Wrong. Converting indexes relates to index manipulation functions like reset_index , not aggregation.
</details>

## Question 4

Which of the following column types are valid inputs to a groupby operation?

- **A)** Numerical columns like salary and experience.
- **B)** Both unique identifiers and department columns.
- **C)** Categorical columns like department, city, and gender.
- **D)** Any column type equally, as groupby works on all

<details><summary><b>Answer & explanation</b></summary>

**Correct: C**

- **A** — Wrong. Grouping by numerical or discrete variables is logically invalid as it creates a unique group for every number.

- **B** — Wrong. Unique identifiers (like employee names) will just create one group per row, which is meaningless.

- **C** — **Correct**. Categorical variables that take a fixed, finite set of values are the correct inputs to form logical
groups.
- **D** — Wrong. You cannot meaningfully group by unique identifiers or continuous numerical data. Source:
</details>

## Question 5
A grouped result shows department names as the index. How do you convert group labels into regular columns?

- **A)** Call .reset_index() on the result.
- **B)** Pass as_index=True inside the groupby call.
- **C)** Apply df.set_index('department') before grouping.
- **D)** Swap ['salary'] for [['salary']] to change the output.

<details><summary><b>Answer & explanation</b></summary>

**Correct: A**

- **A** — **Correct**. Calling reset_index() converts the group labels back into standard columns and adds a fresh
numeric index.
- **B** — Wrong. as_index=True is already the default behavior, meaning the grouping column becomes the
index.
- **C** — Wrong. set_index moves an existing column into the index before grouping, which worsens the issue.
- **D** — Wrong. Using double brackets returns a DataFrame instead of a Series, but it leaves the department names
as the index.
</details>

# Section 3 — Scenario-Based Practice

A **data analyst** at a **retail company** is **investigating employee compensation and departmental composition**. The analyst has an **employee DataFrame** and needs to **produce a filtered**, **sorted**, and **restructured summary report** using Pandas. Specifically, the analyst must:

**1.** **Filter** to keep only **employees whose salary is strictly** above 50,000 and whose **experience is strictly greater** than 2 years.

**2.** **Sort** the filtered result by salary in descending order.

**3.** **Reorder** the columns in the **final output** to: department , employee , salary , experience .

**4.** Compute and **print** the **mean salary** of the **filtered result using NumPy**.

**Constraints & Requirements:**

- Use only `pandas (imported as pd)` and `numpy (imported as np)`.
- Apply the filter in a single expression using the & operator.
- Use `sort_values()` with `ascending=False` for sorting.
- Use double-bracket column selection for the column reorder.
- Use `np.mean()` to compute the mean salary.
- All steps must operate on the inlined sample data below

In [ ]:
import pandas as pd
import numpy as np
data = {
'employee': ['Amit', 'Maya', 'Alex', 'Kiran', 'Sarah', 'Kumar'],
'department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'HR'],
'salary': [45000, 70000, 65000, 72000, 50000, 48000],
'experience': [2, 5, 2, 6, 3, 1]
}
df = pd.DataFrame(data)

In [ ]:
import pandas as pd

import numpy as np



# Sample Data

df = pd.DataFrame({

    'employee': ['Amit', 'Maya', 'Kiran', 'Ravi', 'Priya'],

    'department': ['HR', 'IT', 'Finance', 'IT', 'HR'],

    'salary': [45000, 70000, 55000, 80000, 30000],

    'experience': [3, 5, 1, 4, 2]

})



# Step 1: Filter — salary > 50000 AND experience > 2

filtered = df[(df['salary'] > 50000) & (df['experience'] > 2)]



# Step 2: Sort by salary descending

sorted_df = filtered.sort_values(ascending=False)



# Step 3: Reorder columns

final = sorted_df[['department', 'employee', 'salary', 'experience']]



# Step 4: Mean salary using NumPy

mean_sal = np.mean(final['salary'])



print(final)

print("Mean Salary:", mean_sal)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [ ]:
import pandas as pd

import numpy as np

data = {

'employee': ['Amit', 'Maya', 'Alex', 'Kiran', 'Sarah', 'Kumar'],

'department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'HR'],

'salary': [45000, 70000, 65000, 72000, 50000, 48000],

'experience': [2, 5, 2, 6, 3, 1]

}

df = pd.DataFrame(data)



# Filter employees with salary > 50000 and experience > 2

filtered_df = df[(df["salary"] > 50000) & (df["experience"] > 2)]



sorted_df = filtered_df.sort_values(by="salary", ascending=False)



# Reorder columns

final_df = sorted_df[["department", "employee", "salary", "experience"]]



# Compute mean salary using NumPy

mean_salary = np.mean(final_df["salary"])



# Display results

print("Filtered and Sorted Report:")

print(final_df)

print("\nMean Salary of Filtered Employees:")

print(mean_salary)

Filtered and Sorted Report:
  department employee  salary  experience
3         IT    Kiran   72000           6
1         IT     Maya   70000           5

Mean Salary of Filtered Employees:
71000.0

**Attempt it yourself first** — write your pipeline here before scrolling to the model answer.

<details><summary><b>Ideal Approach Walkthrough</b></summary>

- **Step 1** — Filter with AND. Apply a combined Boolean filter in a single expression. Each sub-condition must be
wrapped in its own parentheses to enforce correct operator precedence. df['salary'] > 50000 produces a Boolean Series; df['experience'] > 2 produces another. The & operator combines them element-wise:
only rows where both are True survive. Amit (salary 45000), Alex (experience exactly 2 — not strictly greater), Sarah (salary exactly 50000 — not strictly greater), and Kumar (salary 48000) are all excluded. Maya (70000, experience 5) and Kiran (72000, experience 6) pass both conditions.

- **Step 2** — Sort descending. Call sort_values(by='salary', ascending=False) on the filtered
DataFrame. Kiran (72000) ranks above Maya (70000), so Kiran's row appears first.
- **Step 3** — Reorder columns. Pass the desired column order as a Python list inside double brackets. This
produces a new DataFrame view with columns in the order department , employee , salary ,
experience — no data values are changed.
- **Step 4** — Compute mean. Pass the salary column of the result to np.mean() . The arithmetic mean of
72000 and 70000 is (72000 + 70000) / 2 = 71000.0.

</details>

In [ ]:
import pandas as pd
import numpy as np
data = {
'employee': ['Amit', 'Maya', 'Alex', 'Kiran', 'Sarah', 'Kumar'],
'department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'HR'],
'salary': [45000, 70000, 65000, 72000, 50000, 48000],
'experience': [2, 5, 2, 6, 3, 1]
}
df = pd.DataFrame(data)
# Step 1: Filter — salary strictly above 50000 AND experience strictly above 2
filtered_df = df[(df['salary'] > 50000) & (df['experience'] > 2)]
# Step 2: Sort by salary descending
sorted_df = filtered_df.sort_values(by='salary', ascending=False)
# Step 3: Reorder columns
result = sorted_df[['department', 'employee', 'salary', 'experience']]
# Step 4: Print result and mean salary
print(result)
print(np.mean(result['salary']))

  department employee  salary  experience
3         IT    Kiran   72000           6
1         IT     Maya   70000           5
71000.0

## Question 2

**Problem Statement:** A **data analyst** at an **online education platform** is building a report to identify **high-performing students** across **departments**. The platform `stores data in three separate tables`: a `student registration table`, a `marks table`, and a `department table`. The analyst must `merge all three tables`, `filter to students` who `scored above 80`, and then compute the `average score per department` using a chained merge workflow.

**Constraints & Requirements:**

- Use pandas only `(import pandas as pd)`; no other libraries are required.
- Merge the three DataFrames using chained `pd.merge()` calls.
- Use an `inner join` when merging the student table with the marks table (only students with scores should appear).
- Use a `left join` when merging the intermediate result with the department table `(preserve all matched students even if a department record is somehow missing)`.
- After merging, `filter the result` to rows where `marks > 80` .
- Compute the `average marks` per dept_name using `.groupby()` .
- Handle the case where the marks and department tables use different key column names from the student table `(marks uses sid , department uses dept_id )`.

In [ ]:
# Sample Data & Inputs:

import pandas as pd
# Table 1: Student registration
students = pd.DataFrame({
"student_id": [1, 2, 3, 4, 5],
"name": ["Student A", "Student B", "Student C", "Student D", "Student E"],
"dept_id": [10, 20, 10, 30, 20]
})
# Table 2: Marks (key column is named 'sid', not 'student_id')
marks = pd.DataFrame({
"sid": [1, 2, 3, 5, 6],
"marks": [92, 75, 88, 61, 95]
})
# Table 3: Department (key column is 'dept_id')
departments = pd.DataFrame({
"dept_id": [10, 20, 30],
"dept_name": ["Computer Science", "Mechanical", "Electrical"]
})

In [ ]:
merged_df = pd.merge(students, marks, left_on="student_id", right_on="sid", how="inner")
print(merged_df)

merged_df = pd.merge(merged_df, departments, on="dept_id", how="left")
print(merged_df)

filtered_df = merged_df[merged_df['marks'] > 80]
print(filtered_df)

average_marks_per_dept = filtered_df.groupby('dept_name')['marks'].mean().reset_index()
print(average_marks_per_dept)
# Display the final result

print(average_marks_per_dept)

   student_id       name  dept_id  sid  marks
0           1  Student A       10    1     92
1           2  Student B       20    2     75
2           3  Student C       10    3     88
3           5  Student E       20    5     61
   student_id       name  dept_id  sid  marks         dept_name
0           1  Student A       10    1     92  Computer Science
1           2  Student B       20    2     75        Mechanical
2           3  Student C       10    3     88  Computer Science
3           5  Student E       20    5     61        Mechanical
   student_id       name  dept_id  sid  marks         dept_name
0           1  Student A       10    1     92  Computer Science
2           3  Student C       10    3     88  Computer Science
          dept_name  marks
0  Computer Science   90.0
          dept_name  marks
0  Computer Science   90.0

<details><summary><b>Ideal Approach Walkthrough</b></summary>

1. **Step 1** — Inner join (students + marks with mismatched key names): The student registration table uses
student_id as the key; the marks table uses sid . Because the key columns have different names,
left_on="student_id" and right_on="sid" are required. Using how="inner" keeps only
students who appear in both tables. Students 1, 2, 3, and 5 match. Student 4 has no marks entry (dropped).
Student 6 has marks but no registration record (dropped by the inner join).
2. **Step 2** — Left join (intermediate result + departments): The intermediate result from step 1 contains
dept_id (from students). Merging with departments on dept_id using how="left" resolves
the department name for each matched student. A left join ensures that even if a dept_id is missing from
the departments table, the student row is still retained (with NaN for dept_name ).
3. **Step 3** — Filter marks > 80: Apply a boolean condition to keep only rows where marks > 80 . Students
1 (marks=92) and 3 (marks=88) pass; students 2 (marks=75) and 5 (marks=61) are dropped.
4. **Step 4** — GroupBy and average: Group the filtered DataFrame by dept_name and compute the mean of
the marks column. Both remaining students belong to "Computer Science". Average = (92 + 88) / 2 =
90.0.
<details>

In [ ]:
import pandas as pd
# Data setup
students = pd.DataFrame({
"student_id": [1, 2, 3, 4, 5],
"name": ["Student A", "Student B", "Student C", "Student D", "Student E"],
"dept_id": [10, 20, 10, 30, 20]
})
marks = pd.DataFrame({
"sid": [1, 2, 3, 5, 6],
"marks": [92, 75, 88, 61, 95]
})
departments = pd.DataFrame({
"dept_id": [10, 20, 30],
"dept_name": ["Computer Science", "Mechanical", "Electrical"]
})
# Step 1: Merge students and marks — inner join, mismatched key names
step1 = pd.merge(students, marks, left_on="student_id", right_on="sid", how="inner")
# Step 2: Merge with departments — left join on dept_id
step2 = pd.merge(step1, departments, on="dept_id", how="left")
# Step 3: Filter to students scoring above 80
filtered = step2[step2["marks"] > 80]
# Step 4: Average marks per department
avg_by_dept = filtered.groupby("dept_name")["marks"].mean()
print(avg_by_dept)

dept_name
Computer Science    90.0
Name: marks, dtype: float64

## Section 4: Q&A Block

> **TA flow:** Open the floor. Prioritise conceptual doubts and assessment queries. If unsure, acknowledge and follow up — don't guess. If no questions: *"Which question felt hardest? Let's revisit it."*

**Anticipated Doubt Areas**

- The distinct boundary logic of loc (inclusive endpoint) versus iloc (exclusive endpoint like standard Python slicing).

- Why *parentheses* are absolutely *mandatory* when using *multiple filters with & and |* `(due to Python operator precedence overriding the Pandas conditions)`.
- How to appropriately decide between vertical concatenation `( pd.concat )` and a `structural merge ( pd.merge )` depending on table similarities.
- Understanding the difference between `inner` , `left` , `right` , and `outer joins` and what happens to non-matching records (i.e., the introduction of NaN missing values).
- Why we cannot apply statistical aggregation functions (like mean or min) on categorical string variables.

**Doubt #1: (type the participant's question here)**

In [ ]:
# Work through it here

**Doubt #2: (type the participant's question here)**

In [ ]:
# Work through it here

**Doubt #3: (type the participant's question here)**

In [ ]:
# Work through it here

**Doubt #4: (type the participant's question here)**

In [ ]:
# Work through it here

**Doubt #5: (type the participant's question here)**

**Topic 1 Summary**

Data Selection → Choose rows/columns

✅ loc[] → Label based, end included

✅ iloc[] → Position based, end excluded

✅ Filtering → Keep rows satisfying conditions

✅ & = AND

✅ | = OR

✅ Parentheses mandatory when combining conditions

**Topic 2 Summary**

✅ Sorting **arranges rows** in a meaningful order

✅ **sort_values()** is used for sorting

✅ **Default** sorting is **ascending**

✅ **ascending=False** gives **descending** order

✅ Multiple-column sorting is possible

✅ **Reordering** columns changes the display order of columns

✅ Use **double brackets [[ ]] **for selecting multiple columns

**Topic 3 Summary**

✅ groupby() divides data into groups

✅ Aggregation creates summaries from multiple values

✅ Common functions:

- sum()
- mean()
- count()
- min()
- max()

✅ agg() applies multiple functions together

✅ reset_index() converts group labels back into normal columns

✅ Group using categorical columns such as: Department, City,
Gender

❌ Avoid grouping by unique identifiers or continuous numerical values

**Topic 4 Summary**

✅ merge() combines DataFrames using common keys

✅ Join types:

Inner
Left
Right
Outer

✅ concat() stacks DataFrames

✅ axis=0 → Vertical stacking

✅ axis=1 → Horizontal stacking

✅ ignore_index=True resets row numbering

✅ join() combines DataFrames using indexes